### ISSUE TITLE
求指教

### ISSUE THREAD

**Issue by huifeidekaola** [tqq123/Vue-Koa2-MongoDB#2]
![image](https://user-images.githubusercontent.com/44389022/52934389-3f7de300-3391-11e9-8346-80486feff714.png)

运行有报错 ： 请求的商品列表是空数组
CategoryList.vue?c482:106 Uncaught (in promise) TypeError: Cannot read property 'ID' of undefined
    at eval (CategoryList.vue?c482:106

**Comment by tqq123** [comment]
不好意思，好几天才回复。多谢提醒，应该是因为我的数据库里是存过数据的，没有考虑到这个问题，我把存数据的操作代码也补进去一下。

**Comment by huifeidekaola** [comment]
看了您的代码学习到了 模仿着做了个类似的 感谢

**Comment by tqq123** [comment]
代码已更新，可以试试。有问题随时issue跟我说哈~
